"""empty message

Revision ID: 1963d6605d44
Revises: 
Create Date: 2019-02-05 16:11:19.216128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1963d6605d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dobavljac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('oib', sa.Integer(), nullable=True),
    sa.Column('grad', sa.String(length=64), nullable=True),
    sa.Column('p_broj', sa.Integer(), nullable=True),
    sa.Column('drzava', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('oib')
    )
    op.create_table('proizvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('kolicina', sa.Integer(), nullable=True),
    sa.Column('zemlja_podrijetla', sa.String(length=64), nullable=True),
    sa.Column('datum_unosa', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('evidencija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=True),
    sa.Column('dobavljac_id', sa.Integer(), nullable=True),
    sa.Column('datum_unosa', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dobavljac_id'], ['dobavljac.id'], ),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencija')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('proizvod')
    op.drop_table('dobavljac')
    # ### end Alembic commands ###
