"""empty message

Revision ID: 1ce3cbfa72fd
Revises: e7aecb37f87b
Create Date: 2019-02-25 12:59:53.434945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3cbfa72fd'
down_revision = 'e7aecb37f87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tvrtka', sa.Column('adresa', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tvrtka', 'adresa')
    # ### end Alembic commands ###
