"""empty message

Revision ID: 3a4ef2eadd6c
Revises: ebd2339da7c0
Create Date: 2019-02-05 12:54:17.840522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4ef2eadd6c'
down_revision = 'ebd2339da7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dobavljac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('oib', sa.Integer(), nullable=True),
    sa.Column('grad', sa.String(length=64), nullable=True),
    sa.Column('p_broj', sa.Integer(), nullable=True),
    sa.Column('drzava', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('oib')
    )
    op.drop_index('ix_proizvod_name', table_name='proizvod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_proizvod_name', 'proizvod', ['name'], unique=1)
    op.drop_table('dobavljac')
    # ### end Alembic commands ###
