"""empty message

Revision ID: 4fd8a1c4f3d9
Revises: 00f06addaa20
Create Date: 2019-02-14 11:06:25.762662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd8a1c4f3d9'
down_revision = '00f06addaa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proizvod', sa.Column('opis_proizvoda', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proizvod', 'opis_proizvoda')
    # ### end Alembic commands ###
