"""empty message

Revision ID: 8422db7c5dfc
Revises: f10963f0babd
Create Date: 2019-02-07 13:42:43.688107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8422db7c5dfc'
down_revision = 'f10963f0babd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tvrtka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('oib', sa.Integer(), nullable=True),
    sa.Column('grad', sa.String(length=64), nullable=True),
    sa.Column('p_broj', sa.Integer(), nullable=True),
    sa.Column('drzava', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('oib')
    )
    op.create_table('evidencija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proizvod_id', sa.Integer(), nullable=True),
    sa.Column('tvrtka_id', sa.Integer(), nullable=True),
    sa.Column('promijenjena_kolicina', sa.Integer(), nullable=True),
    sa.Column('datum_unosa', sa.DateTime(), nullable=True),
    sa.Column('vrsta_unosa', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.ForeignKeyConstraint(['tvrtka_id'], ['tvrtka.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kupac')
    op.drop_table('evidencija_unosa')
    op.drop_table('dobavljac')
    op.drop_table('evidencija_izdavanja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencija_izdavanja',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proizvod_id', sa.INTEGER(), nullable=True),
    sa.Column('kupac_id', sa.INTEGER(), nullable=True),
    sa.Column('promijenjena_kolicina', sa.INTEGER(), nullable=True),
    sa.Column('datum_unosa', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['kupac_id'], ['kupac.id'], ),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dobavljac',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('oib', sa.INTEGER(), nullable=True),
    sa.Column('grad', sa.VARCHAR(length=64), nullable=True),
    sa.Column('p_broj', sa.INTEGER(), nullable=True),
    sa.Column('drzava', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('oib')
    )
    op.create_table('evidencija_unosa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proizvod_id', sa.INTEGER(), nullable=True),
    sa.Column('dobavljac_id', sa.INTEGER(), nullable=True),
    sa.Column('promijenjena_kolicina', sa.INTEGER(), nullable=True),
    sa.Column('datum_unosa', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['dobavljac_id'], ['dobavljac.id'], ),
    sa.ForeignKeyConstraint(['proizvod_id'], ['proizvod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kupac',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('oib', sa.INTEGER(), nullable=True),
    sa.Column('grad', sa.VARCHAR(length=64), nullable=True),
    sa.Column('p_broj', sa.INTEGER(), nullable=True),
    sa.Column('drzava', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('oib')
    )
    op.drop_table('evidencija')
    op.drop_table('tvrtka')
    # ### end Alembic commands ###
