"""empty message

Revision ID: aaf423c08517
Revises: 1ead8fe54fa2
Create Date: 2019-02-24 21:19:10.483222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf423c08517'
down_revision = '1ead8fe54fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidencija', sa.Column('trenutna_kolicina', sa.Integer(), nullable=True))
    op.add_column('proizvod', sa.Column('opis_proizvoda', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proizvod', 'opis_proizvoda')
    op.drop_column('evidencija', 'trenutna_kolicina')
    # ### end Alembic commands ###
