"""empty message

Revision ID: af05e42fd6b1
Revises: cd6efa4f2361
Create Date: 2019-02-06 14:14:30.803634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af05e42fd6b1'
down_revision = 'cd6efa4f2361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidencija', sa.Column('promijenjena_kolicina', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidencija', 'promijenjena_kolicina')
    # ### end Alembic commands ###
