"""empty message

Revision ID: b2a22a85ea6a
Revises: 557c1201101c
Create Date: 2019-02-14 10:56:14.249583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a22a85ea6a'
down_revision = '557c1201101c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proizvod', sa.Column('opis_proizvoda', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proizvod', 'opis_proizvoda')
    # ### end Alembic commands ###
