"""empty message

Revision ID: e6b2f4a140a3
Revises: d702bea1e26b
Create Date: 2019-02-07 10:51:38.638914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b2f4a140a3'
down_revision = 'd702bea1e26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidencija_izdavanja', type_='foreignkey')
    op.create_foreign_key(None, 'evidencija_izdavanja', 'kupac', ['kupac_id'], ['id'])
    op.drop_column('evidencija_izdavanja', 'vrsta_unosa')
    op.drop_column('evidencija_unosa', 'vrsta_unosa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidencija_unosa', sa.Column('vrsta_unosa', sa.VARCHAR(length=64), nullable=True))
    op.add_column('evidencija_izdavanja', sa.Column('vrsta_unosa', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'evidencija_izdavanja', type_='foreignkey')
    op.create_foreign_key(None, 'evidencija_izdavanja', 'dobavljac', ['kupac_id'], ['id'])
    # ### end Alembic commands ###
