"""empty message

Revision ID: e822316cf511
Revises: cd1cf96fcc2e
Create Date: 2019-02-13 14:16:25.544144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e822316cf511'
down_revision = 'cd1cf96fcc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proizvod', sa.Column('opis_proizvoda', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proizvod', 'opis_proizvoda')
    # ### end Alembic commands ###
