"""empty message

Revision ID: ebd2339da7c0
Revises: b5d9b2867fde
Create Date: 2019-02-05 09:45:35.572423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd2339da7c0'
down_revision = 'b5d9b2867fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proizvod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('kolicina', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proizvod_name'), 'proizvod', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proizvod_name'), table_name='proizvod')
    op.drop_table('proizvod')
    # ### end Alembic commands ###
