"""empty message

Revision ID: ee1ab2d995e3
Revises: ea133fc7412a
Create Date: 2019-02-06 14:03:09.607923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ab2d995e3'
down_revision = 'ea133fc7412a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidencija', sa.Column('promijenjena_kolicina', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidencija', 'promijenjena_kolicina')
    # ### end Alembic commands ###
