"""empty message

Revision ID: fda7ccb49d54
Revises: 958c0643a2a9
Create Date: 2019-02-07 10:03:38.383976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda7ccb49d54'
down_revision = '958c0643a2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidencija_izdavanja', type_='foreignkey')
    op.create_foreign_key(None, 'evidencija_izdavanja', 'kupac', ['kupac_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidencija_izdavanja', type_='foreignkey')
    op.create_foreign_key(None, 'evidencija_izdavanja', 'dobavljac', ['kupac_id'], ['id'])
    # ### end Alembic commands ###
